AspNetMVCTilaus/WebAppTilausDB/Controllers/HenkilotController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAppTilausDB.Models;
using WebAppTilausDB.ViewModels;

namespace WebAppTilausDB.Controllers
{
    public class HenkilotController : Controller
    {
        private readonly TilausDBEntities db = new TilausDBEntities();

        // GET: Henkilot
        public ActionResult Index(int? page,
                                  int? pagesize,
                                  string osoiteFilter,
                                  string esimiesID)
        {
            if (Session["KayttajaNimi"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            var esimies = db.Henkilot.Select(x => x.Esimies).Distinct().ToList();
            esimies.Insert(0, null);
            ViewBag.EsimiesIDt = new SelectList(esimies, int.TryParse(esimiesID, out int eId) ? eId : 0);
            ViewBag.EsimiesID = esimiesID;
            ViewBag.OsoiteFilter = osoiteFilter;
            var henkilot = from h in db.Henkilot
                           select h;
            if (!string.IsNullOrEmpty(esimiesID) && esimiesID != " ")
            {
                int id = int.Parse(esimiesID);
                henkilot = henkilot.Where(h => h.Esimies == id);
            }
            if (!string.IsNullOrEmpty(osoiteFilter))
            {
                henkilot = henkilot.Where(h => h.Osoite.Contains(osoiteFilter));
            }
            int pageNumber = page ?? 1;
            int pageSize = pagesize ?? 15;
            return View(henkilot.OrderBy(x => x.Henkilo_id).ToPagedList(pageNumber, pageSize));
        }

        // GET: Henkilot/Details/5
        public ActionResult _DetailsPartial(int? id)
        {
            if (Session["KayttajaNimi"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            if (id == null)
            {
                ViewBag.Error = ErrorMessages.HuonoHaku();
                return View("Error");
            }
            Henkilot henkilo = db.Henkilot.Find(id);
            if (henkilo == null)
            {
                ViewBag.Error = ErrorMessages.EiLoydy();
                return View("Error");
            }
            return PartialView(henkilo); 
        }

        // GET: Henkilot/Create
        public ActionResult _CreatePartial()
        {
            if (Session["KayttajaNimi"] != null && (Session["Oikeudet"].Equals("Muokkaa") || Session["Oikeudet"].Equals("Admin")))
            {
                List<SelectListItem> ptp = db.Postitoimipaikat.Select(x => new SelectListItem
                {
                    Value = x.Postinumero,
                    Text = x.Postinumero + " " + x.Postitoimipaikka
                }).ToList();
                ViewBag.Postinumero = new SelectList(ptp, "Value", "Text");
                return PartialView(); 
            }
            ViewBag.Error = ErrorMessages.Lupa();
            return View("Error");
        }

        // POST: Henkilot/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Henkilo_id,Etunimi,Sukunimi,Osoite,Esimies,Postinumero,Sahkoposti")] Henkilot henkilot)
        {
            if (Session["KayttajaNimi"] != null && (Session["Oikeudet"].Equals("Muokkaa") || Session["Oikeudet"].Equals("Admin")))
            {
                if (ModelState.IsValid)
                {
                    db.Henkilot.Add(henkilot);
                    db.SaveChanges();
                    return Redirect(Request.UrlReferrer.ToString());
                }
                ViewBag.HeniloVirhe = "Henkilön luonti epäonnistui. Yritä uudelleen.";
                return RedirectToAction("Index");
                //List<SelectListItem> ptp = db.Postitoimipaikat.Select(x => new SelectListItem
                //{
                //    Value = x.Postinumero,
                //    Text = x.Postinumero + " " + x.Postitoimipaikka
                //}).ToList();
                //ViewBag.Postinumero = new SelectList(ptp, "Value", "Text", henkilot.Postinumero);
                //return View(henkilot); 
            }
            ViewBag.Error = ErrorMessages.Lupa();
            return View("Error");
        }

        // GET: Henkilot/Edit/5
        public ActionResult _EditPartial(int? id)
        {
            if (Session["KayttajaNimi"] != null && (Session["Oikeudet"].Equals("Muokkaa") || Session["Oikeudet"].Equals("Admin")))
            {
                if (id == null)
                {
                    ViewBag.Error = ErrorMessages.HuonoHaku();
                return View("Error");
                }
                Henkilot henkilot = db.Henkilot.Find(id);
                if (henkilot == null)
                {
                    ViewBag.Error = ErrorMessages.EiLoydy();
                return View("Error");
                }
                List<SelectListItem> ptp = db.Postitoimipaikat.Select(x => new SelectListItem
                {
                    Value = x.Postinumero,
                    Text = x.Postinumero + " " + x.Postitoimipaikka
                }).ToList();
                ViewBag.Postinumero = new SelectList(ptp, "Value", "Text", henkilot.Postinumero);
                return PartialView(henkilot); 
            }
            ViewBag.Error = ErrorMessages.Lupa();
            return View("Error");
        }

        // POST: Henkilot/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Henkilo_id,Etunimi,Sukunimi,Osoite,Esimies,Postinumero,Sahkoposti")] Henkilot henkilot)
        {
            if (Session["KayttajaNimi"] != null && (Session["Oikeudet"].Equals("Muokkaa") || Session["Oikeudet"].Equals("Admin")))
            {
                if (ModelState.IsValid)
                {
                    db.Entry(henkilot).State = EntityState.Modified;
                    db.SaveChanges();
                    return Redirect(Request.UrlReferrer.ToString());
                }
                ViewBag.HeniloVirhe = "Henkilön muokkaus epäonnistui. Yritä uudelleen.";
                return RedirectToAction("Index");
                //List<SelectListItem> ptp = db.Postitoimipaikat.Select(x => new SelectListItem
                //{
                //    Value = x.Postinumero,
                //    Text = x.Postinumero + " " + x.Postitoimipaikka
                //}).ToList();
                //ViewBag.Postinumero = new SelectList(ptp, "Value", "Text", henkilot.Postinumero);
                //return View(henkilot); 
            }
            ViewBag.Error = ErrorMessages.Lupa();
            return View("Error");
        }

        // GET: Henkilot/Delete/5
        public ActionResult _DeletePartial(int? id)
        {
            if (Session["KayttajaNimi"] != null && (Session["Oikeudet"].Equals("Muokkaa") || Session["Oikeudet"].Equals("Admin")))
            {
                if (id == null)
                {
                    ViewBag.Error = ErrorMessages.HuonoHaku();
                return View("Error");
                }
                Henkilot henkilot = db.Henkilot.Find(id);
                if (henkilot == null)
                {
                    ViewBag.Error = ErrorMessages.EiLoydy();
                return View("Error");
                }
                return PartialView(henkilot); 
            }
            ViewBag.Error = ErrorMessages.Lupa();
            return View("Error");
        }

        // POST: Henkilot/Delete/5
        [HttpPost, ActionName("_DeletePartial")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["KayttajaNimi"] != null && (Session["Oikeudet"].Equals("Muokkaa") || Session["Oikeudet"].Equals("Admin")))
            {
                Henkilot henkilot = db.Henkilot.Find(id);
                db.Henkilot.Remove(henkilot);
                db.SaveChanges();
                return RedirectToAction("Index"); 
            }
            ViewBag.Error = ErrorMessages.Lupa();
            return View("Error");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AspNetMVCTilaus/WebAppTilausDB/Views/Henkilot/Index.cshtml
@model PagedList.PagedList<WebAppTilausDB.Models.Henkilot>
@using PagedList.Mvc;
@{
    ViewBag.Count = 0;
    ViewBag.Title = "Henkilöt";
}

<h2 id="otsikko">Henkilöt</h2>
<p class="text-danger">@ViewBag.HenkiloVirhe</p>
@using (Html.BeginForm("Index", "Henkilot", FormMethod.Get))
{
    <div class="input-group">
        <p class="px-1">@Html.Label("Etsi henkilöä osoitteen perusteella:")</p>
        <p class="px-1">@Html.TextBox("osoiteFilter", ViewBag.OsoiteFilter as string, new { @class = "form-control" })</p>
        <p class="px-1">@Html.Label("Esimies ID:n perusteella:")</p>
        <p class="px-1">@Html.Hidden("EsimiesID", ViewBag.EsimiesID as string, new { @id = "EsimiesID", @class = "form-control" })</p>
        <p class="px-1">@Html.DropDownList("EsimiesIDt", null, htmlAttributes: new { @id = "esimiesFilter", @class = "form-control" })</p>
        <p class="px-1"><input type="submit" value="Etsi" class="form-control" /></p>
    </div>
}
<table class="table table-hover">
    <tr class="table-primary">
        <th><a id="henkiloCreateToModal" class="btn btn-sm btn-primary @(Session["Oikeudet"].Equals("Näytä") ? "disabled" : "")"><img src="~/Content/Icons/file-plus.svg" /></a></th>
        <th>Etunimi</th>
        <th>Sukunimi</th>
        <th>Osoite</th>
        <th>Esimies ID</th>
        <th>Sahkoposti</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="@(ViewBag.Count % 2 != 0 ? "table-dark" : "table-default")">
            <td>
                @if (Session["Oikeudet"].Equals("Näytä"))
                {
                    <a class="btn btn-sm btn-primary henkiloDetailsToModal" data-henkiloid="@item.Henkilo_id"><img src="~/Content/Icons/info-square.svg" /></a>

                }
                else
                {
                    <a class="btn btn-sm btn-primary henkiloEditToModal" data-henkiloid="@item.Henkilo_id"><i class="fas fa-edit"></i></a>
                    <a class="btn btn-sm btn-primary henkiloDetailsToModal" data-henkiloid="@item.Henkilo_id"><img src="~/Content/Icons/info-square.svg" /></a>
                    <a class="btn btn-sm btn-primary henkiloDeleteToModal" data-henkiloid="@item.Henkilo_id"><img src="~/Content/Icons/trash-fill.svg" /></a>
                }
            </td>
            <td>@Html.DisplayFor(modelItem => item.Etunimi)</td>
            <td>@Html.DisplayFor(modelItem => item.Sukunimi)</td>
            <td>@Html.DisplayFor(modelItem => item.Osoite)</td>
            <td>@Html.DisplayFor(modelItem => item.Esimies)</td>
            <td>@Html.DisplayFor(modelItem => item.Sahkoposti)</td>
        </tr>
        ViewBag.Count++;
    }

</table>
<div id="divHenkiloModal"></div>
<div>
    @Html.ActionLink("Etusivu", "Index", "Home")
</div>

Sivu @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index", new {
    page,
    osoiteFilter = ViewBag.OsoiteFilter,
    esimiesID = ViewBag.EsimiesID
}))

@section scripts{
    <script type="text/javascript">
        $("#henkiloCreateToModal").click(function () {
            let url = '/Henkilot/_CreatePartial';
            $.get(url, (data) => {
                $("#divHenkiloModal").replaceWith(data);
                $("#divHenkiloModal").modal('show');
            });
        });
        $(".henkiloEditToModal").click(function () {
            let henkiloId = $(this).data("henkiloid");
            let url = '/Henkilot/_EditPartial/' + henkiloId;
            $.get(url, (data) => {
                $("#divHenkiloModal").replaceWith(data);
                $("#divHenkiloModal").modal('show');
            });
        });
        $(".henkiloDetailsToModal").click(function () {
            let henkiloId = $(this).data("henkiloid");
            let url = '/Henkilot/_DetailsPartial/' + henkiloId;
            $.get(url, (data) => {
                $("#divHenkiloModal").replaceWith(data);
                $("#divHenkiloModal").modal('show');
            });
        });
        $(".henkiloDeleteToModal").click(function () {
            let henkiloId = $(this).data("henkiloid");
            let url = '/Henkilot/_DeletePartial/' + henkiloId;
            $.get(url, (data) => {
                $("#divHenkiloModal").replaceWith(data);
                $("#divHenkiloModal").modal('show');
            });
        });
        $("#esimiesFilter").on("change", () => {
            let selValue = $("#esimiesFilter").val();
            document.getElementById("EsimiesID").value = selValue;
        });
    </script>
}

AspNetMVCTilaus/WebAppTilausDB/Views/Henkilot/_CreatePartial.cshtml
@model WebAppTilausDB.Models.Henkilot


<div class="modal" id="divHenkiloModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Lisää uusi henkilö</h2>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Create", "Henkilot", FormMethod.Post, new { @id = "henkiloCreateForm" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Etunimi, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Etunimi, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Etunimi, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Sukunimi, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Sukunimi, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Sukunimi, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Osoite, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Osoite, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Osoite, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Esimies, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Esimies, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Esimies, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Postinumero, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Postinumero", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Postinumero, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Sahkoposti, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Sahkoposti, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Sahkoposti, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button class="btn btn-success" form="henkiloCreateForm"><img src="~/Content/Icons/check-box.svg" /></button>
                <button class="btn btn-info" data-dismiss="modal"><img src="~/Content/Icons/x-square.svg" /></button>
            </div>
        </div>
    </div>
</div>

AspNetMVCTilaus/WebAppTilausDB/Views/Henkilot/_DeletePartial.cshtml
@model WebAppTilausDB.Models.Henkilot

    <div class="modal" id="divHenkiloModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h2>Henkilön poisto</h2>
                </div>
                <div class="modal-body">
                    <h3>Oletko varma, että haluat poistaa henkilön ID:@Html.DisplayFor(model => model.Henkilo_id)?</h3>
                    <dl class="dl-horizontal">
                        <dt>@Html.DisplayNameFor(model => model.Etunimi)</dt>
                        <dd>@Html.DisplayFor(model => model.Etunimi)</dd>
                        <dt>@Html.DisplayNameFor(model => model.Sukunimi)</dt>
                        <dd>@Html.DisplayFor(model => model.Sukunimi)</dd>
                        <dt>@Html.DisplayNameFor(model => model.Osoite)</dt>
                        <dd>@Html.DisplayFor(model => model.Osoite)</dd>
                        <dt>@Html.DisplayNameFor(model => model.Postinumero)</dt>
                        <dd>@Html.DisplayFor(model => model.Postinumero)</dd>
                        <dt>@Html.DisplayNameFor(model => model.Sahkoposti)</dt>
                        <dd>@Html.DisplayFor(model => model.Sahkoposti)</dd>
                        <dt>@Html.DisplayNameFor(model => model.Esimies)</dt>
                        <dd>@Html.DisplayFor(model => model.Esimies)</dd>
                    </dl>
                </div>
                <div class="modal-footer">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        <button type="submit" value="Poista" class="btn btn-danger"><img src="~/Content/Icons/trash-fill.svg" /></button>
                    }
                    <button class="btn btn-info" data-dismiss="modal"><img src="~/Content/Icons/x-square.svg" /></button>
                </div>
            </div>
        </div>
    </div>

AspNetMVCTilaus/WebAppTilausDB/Views/Henkilot/_DetailsPartial.cshtml
@model WebAppTilausDB.Models.Henkilot

<div class="modal" id="divHenkiloModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Henkilön lisätiedot</h2>
            </div>
            <div class="modal-body">
                <dl class="dl-horizontal">
                    <dt>@Html.DisplayNameFor(model => model.Henkilo_id)</dt>
                    <dd>@Html.DisplayFor(model => model.Henkilo_id)</dd>
                    <dt>@Html.DisplayNameFor(model => model.Etunimi)</dt>
                    <dd>@Html.DisplayFor(model => model.Etunimi)</dd>
                    <dt>@Html.DisplayNameFor(model => model.Sukunimi)</dt>
                    <dd>@Html.DisplayFor(model => model.Sukunimi)</dd>
                    <dt>@Html.DisplayNameFor(model => model.Osoite)</dt>
                    <dd>@Html.DisplayFor(model => model.Osoite)</dd>
                    <dt>@Html.DisplayNameFor(model => model.Postinumero)</dt>
                    <dd>@Html.DisplayFor(model => model.Postinumero)</dd>
                    <dt>@Html.DisplayNameFor(model => model.Sahkoposti)</dt>
                    <dd>@Html.DisplayFor(model => model.Sahkoposti)</dd>
                    <dt>@Html.DisplayNameFor(model => model.Esimies)</dt>
                    <dd>@Html.DisplayFor(model => model.Esimies)</dd>
                </dl>
            </div>
            <div class="modal-footer">
                <button class="btn btn-info" data-dismiss="modal"><img src="~/Content/Icons/x-square.svg" /></button>
            </div>
        </div>
    </div>
</div>

AspNetMVCTilaus/WebAppTilausDB/Views/Henkilot/_EditPartial.cshtml
@model WebAppTilausDB.Models.Henkilot

<div class="modal" id="divHenkiloModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Muokkaa henkilön ID:@Html.DisplayFor(model => model.Henkilo_id) henkilötietoja</h2>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Edit", "Henkilot", FormMethod.Post, new { @id = "henkiloEditForm" }))
                {
                    @Html.AntiForgeryToken()
                    <form>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Henkilo_id)

                        <div class="form-group">
                            @Html.LabelFor(model => model.Etunimi, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Etunimi, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Etunimi, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Sukunimi, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Sukunimi, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Sukunimi, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Osoite, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Osoite, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Osoite, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Postinumero, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("Postinumero", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Postinumero, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Sahkoposti, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Sahkoposti, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Sahkoposti, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Esimies, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Esimies, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Esimies, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </form>
                }
            </div>
            <div class="modal-footer">
                <button class="btn btn-success" form="henkiloEditForm"><i class="fas fa-edit"></i></button>
                <button class="btn btn-info" data-dismiss="modal"><img src="~/Content/Icons/x-square.svg" /></button>
            </div>
        </div>
    </div>
</div>